# The following is automatically generated by code_factory.py

from numba import njit


@njit
def bin(index, cs_tally, data, value):
    offset = cs_tally["bin_offset"]
    data[offset + index] = value


@njit
def bin_all(cs_tally, data, value):
    start = cs_tally["bin_offset"]
    size = cs_tally["bin_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_last(cs_tally, data, value):
    start = cs_tally["bin_offset"]
    size = cs_tally["bin_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_chunk(start, length, cs_tally, data, value):
    start += cs_tally["bin_offset"]
    end = start + length
    data[start:end] = value


@njit
def scores(index, cs_tally, data, value):
    offset = cs_tally["scores_offset"]
    data[offset + index] = value


@njit
def scores_all(cs_tally, data, value):
    start = cs_tally["scores_offset"]
    size = cs_tally["scores_length"]
    end = start + size
    data[start:end] = value


@njit
def scores_last(cs_tally, data, value):
    start = cs_tally["scores_offset"]
    size = cs_tally["scores_length"]
    end = start + size
    data[end - 1] = value


@njit
def scores_chunk(start, length, cs_tally, data, value):
    start += cs_tally["scores_offset"]
    end = start + length
    data[start:end] = value


@njit
def mu(index, cs_tally, data, value):
    offset = cs_tally["mu_offset"]
    data[offset + index] = value


@njit
def mu_all(cs_tally, data, value):
    start = cs_tally["mu_offset"]
    size = cs_tally["mu_length"]
    end = start + size
    data[start:end] = value


@njit
def mu_last(cs_tally, data, value):
    start = cs_tally["mu_offset"]
    size = cs_tally["mu_length"]
    end = start + size
    data[end - 1] = value


@njit
def mu_chunk(start, length, cs_tally, data, value):
    start += cs_tally["mu_offset"]
    end = start + length
    data[start:end] = value


@njit
def azi(index, cs_tally, data, value):
    offset = cs_tally["azi_offset"]
    data[offset + index] = value


@njit
def azi_all(cs_tally, data, value):
    start = cs_tally["azi_offset"]
    size = cs_tally["azi_length"]
    end = start + size
    data[start:end] = value


@njit
def azi_last(cs_tally, data, value):
    start = cs_tally["azi_offset"]
    size = cs_tally["azi_length"]
    end = start + size
    data[end - 1] = value


@njit
def azi_chunk(start, length, cs_tally, data, value):
    start += cs_tally["azi_offset"]
    end = start + length
    data[start:end] = value


@njit
def energy(index, cs_tally, data, value):
    offset = cs_tally["energy_offset"]
    data[offset + index] = value


@njit
def energy_all(cs_tally, data, value):
    start = cs_tally["energy_offset"]
    size = cs_tally["energy_length"]
    end = start + size
    data[start:end] = value


@njit
def energy_last(cs_tally, data, value):
    start = cs_tally["energy_offset"]
    size = cs_tally["energy_length"]
    end = start + size
    data[end - 1] = value


@njit
def energy_chunk(start, length, cs_tally, data, value):
    start += cs_tally["energy_offset"]
    end = start + length
    data[start:end] = value


@njit
def time(index, cs_tally, data, value):
    offset = cs_tally["time_offset"]
    data[offset + index] = value


@njit
def time_all(cs_tally, data, value):
    start = cs_tally["time_offset"]
    size = cs_tally["time_length"]
    end = start + size
    data[start:end] = value


@njit
def time_last(cs_tally, data, value):
    start = cs_tally["time_offset"]
    size = cs_tally["time_length"]
    end = start + size
    data[end - 1] = value


@njit
def time_chunk(start, length, cs_tally, data, value):
    start += cs_tally["time_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_sum(index, cs_tally, data, value):
    offset = cs_tally["bin_sum_offset"]
    data[offset + index] = value


@njit
def bin_sum_all(cs_tally, data, value):
    start = cs_tally["bin_sum_offset"]
    size = cs_tally["bin_sum_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_sum_last(cs_tally, data, value):
    start = cs_tally["bin_sum_offset"]
    size = cs_tally["bin_sum_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_sum_chunk(start, length, cs_tally, data, value):
    start += cs_tally["bin_sum_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_sum_square(index, cs_tally, data, value):
    offset = cs_tally["bin_sum_square_offset"]
    data[offset + index] = value


@njit
def bin_sum_square_all(cs_tally, data, value):
    start = cs_tally["bin_sum_square_offset"]
    size = cs_tally["bin_sum_square_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_sum_square_last(cs_tally, data, value):
    start = cs_tally["bin_sum_square_offset"]
    size = cs_tally["bin_sum_square_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_sum_square_chunk(start, length, cs_tally, data, value):
    start += cs_tally["bin_sum_square_offset"]
    end = start + length
    data[start:end] = value


@njit
def bin_shape(index, cs_tally, data, value):
    offset = cs_tally["bin_shape_offset"]
    data[offset + index] = value


@njit
def bin_shape_all(cs_tally, data, value):
    start = cs_tally["bin_shape_offset"]
    size = cs_tally["bin_shape_length"]
    end = start + size
    data[start:end] = value


@njit
def bin_shape_last(cs_tally, data, value):
    start = cs_tally["bin_shape_offset"]
    size = cs_tally["bin_shape_length"]
    end = start + size
    data[end - 1] = value


@njit
def bin_shape_chunk(start, length, cs_tally, data, value):
    start += cs_tally["bin_shape_offset"]
    end = start + length
    data[start:end] = value
